### ISSUE TITLE
Content is also an attachable

### ISSUE THREAD

**Issue by uschmann** [viewneo/viewneo-api#1]
Hi @justniels ,

nice docs so far.
We should add the content entity to the UML-Diagram
that describes a mediaFile. A Content entity represents a content
that was generated from a template.

**Comment by justniels** [comment]
Your are right! I will change this with the creation of the 'Content' Model.

**Comment by uschmann** [comment]
Hi @justniels,

now it looks good to me.
Could you adjust the UML-diagram and put all attachables into on vertical level.
I think this would make the relation between the entities more clear.
